query GetShippings {
  mfb_shipping_shippings {
    id
    number
    content
    count
    createdAt
    recievedAt
    sendedAt
    status
    user_to {
      id
      location
    }
    user_from {
      id
      location
    }
  }
}