query GetShipping($id: uuid!) {
  mfb_shipping_shippings_by_pk(id: $id) {
    content
    count
    createdAt
    id
    recievedAt
    sendedAt
    status
    user_from {
      id
      location
    }
    user_to {
      id
      location
    }
  }
}
